`errorWhenMissingUnityBuildResults` exposed as `with` parameter
game-ci/unity-builder pull request #575
Opened 2023-09-20 15:26 UTC by tobyspark

#### Changes

Seemingly a breaking change in v2 → v3 is the action reporting error if the built player app isn’t present. Not all Unity builds are for the player, e.g. addressable content. Examining the build scripts shows a boolean `errorWhenMissingUnityBuildResults` managing this behaviour. This is now exposed as a `with` parameter in the action YAML. Also, a slightly opinionated refactor of `docker.run` to include an options object instead of the fixed signature requiring all options prior to `errorWhen...` to be defined.

#### Checklist

- [x] Read the contribution [guide](https://github.com/game-ci/unity-builder/blob/main/CONTRIBUTING.md) and accept the
      [code](https://github.com/game-ci/unity-builder/blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Docs (If new inputs or outputs have been added or changes to behavior that should be documented. Please make
            a PR in the [documentation repo](https://github.com/game-ci/documentation))
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

2023-09-20 15:47 UTC, webbertakken requested changes
Unnecessary addition to public api that doesn't add any value.

2023-09-20 15:47 UTC, webbertakken commented on action.yml
> +      producing alternative build products.'
This is effectively a discrepancy in the application (builder and/or container). I feel adding an option in the (functional) public api isn't the answer to this technical issue. 

We should probably agree on how the application should handle this case and not expose anything.

2023-09-20 20:05 UTC, tobyspark commented
> This is effectively a discrepancy in the application (builder and/or container). I feel adding an option in the (functional) public api isn't the answer to this technical issue.

Is this a technical issue? There may indeed be some internal need to change this parameter depending on builder or container. But that’s not why I made the PR. There appears to be a design change in v3 that a successful action completion requires there to be a built player app. That means the Unity Builder action isn’t suitable for a whole range of uses, for example building addressables content. A quick look at the issues list shows many people hitting this, e.g. #563 #564 #567 #572

2023-09-20 20:50 UTC, webbertakken commented
You're probably right. And you're definitely more in the know than I am. 
Sorry if my review isn't accurate!

Perhaps @davidmfinol and @AndrewKahr could continue the review on this one?

2023-09-20 20:51 UTC, webbertakken commented
Also @GabLeRoux

2023-09-20 21:06 UTC, tobyspark commented
I’ve also just read the discord post mentioned in #563, which prompted me to re-read the code for `exec-with-error-check`. I’m not sure how I got “the existence of a built player app” from that, so apologies on that misdirected inaccuracy.

The basic point remains though – that it’s requiring something specific to be output by the build method, that not all build methods will output. This makes me wonder if a more elegant design might be either
- only perform the check if a custom `buildMethod` is _not_ specified in the workflow
- document a simpler string that will be checked for before trying the highly specific regex.

2023-09-20 21:16 UTC, webbertakken commented
I think one of the problems we're facing of why we're checking for a specific text in the first place is that the exit code isn't always reliable. But it is a long time ago that I've implemented the first code for that and unfortunately I've lost context.

2023-09-21 08:12 UTC, tobyspark commented
> document a simpler string that will be checked for before trying the highly specific regex.

Separately, I’ve hit the issue that you can’t write a `GITHUB_STEP_SUMMARY` from one’s Unity code, as it’s running inside a container. Putting the motivation behind this PR together with that, and 
- we could write out the Unity build results as a step summary from `exec-with-error-check.ts`
- and we’d also check for a string in `stdout` like `GAME_CI_STEP_SUMMARY`
If either pass, we don’t error.

2023-09-21 13:15 UTC, tobyspark commented
I’m going to abandon this PR in favour of the approach above. It’s more elegant, solves more problems, and having implemented it for my own purposes, can be self-documenting for someone who experiences the conundrum of seeing ‘Build succeeded’ (i.e. exit code 0) but have the step fail on the results check.

2023-09-21 13:15 UTC, closed without merging